package vn.edu.iud.fit.lehoangkhang.week08_lab05_lehoangkhang_21083791.enums;

public enum JobType {
    FRONTEND, BACKEND, FULLSTACK, DEVOPS, TESTING, MANAGER, BUSSINESS_ANALYST, DATA_ANALYST, DATA_SCIENCE, MACHINE_LEARNING, AI, CLOUD, BLOCKCHAIN, CYBER_SECURITY, TECHNICAL_SUPPORT, CUSTOMER_SUPPORT, OTHERS
}
