package vn.edu.iud.fit.lehoangkhang.week08_lab05_lehoangkhang_21083791.enums;

public enum JobType {
    FRONTEND, BACKEND, FULLSTACK, DEVOPS, TESTING, MANAGER, BUSINESS_ANALYST, DATA_ANALYST, DATA_SCIENCE,
    MACHINE_LEARNING, AI, CLOUD, BLOCKCHAIN, CYBER_SECURITY, TECHNICAL_SUPPORT, CUSTOMER_SUPPORT, OTHERS, MOBILE, WEB,
    DESKTOP, EMBEDDED, IOT, GAME, GRAPHIC, UI_UX, DESIGN, PRODUCT, PRODUCT_MANAGER, PROJECT_MANAGER, SCRUM_MASTER,
    AGILE_COACH, LEADER, HR, RECRUITER, TRAINER, CONSULTANT, SALES, MARKETING, ACCOUNTANT, FINANCE, NETWORK, SYSTEM,
    DATABASE, ARCHITECT
}
